fix: calling a bash script to execute the API endpoint

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -58,34 +58,29 @@ jobs:
 
     #     echo "Error: PostgreSQL did not become ready after 30 attempts."
     #     exit 1
+    - name: Calling API enpoint for data insertion
+      run: sh api_run.sh
+      # run: |
+      #   echo "Trying to execute test endpoint..."
 
-    - name: Test API endpoint (inserting test data for DBT use)
-      run: |
-        docker exec -it api /bin/bash
-        apt update && apt install curl -y
-        curl -s -o /dev/null -w '%{http_code}' http://localhost:8200/api/insert-data-test/
-
-    #   run: |
-    #     echo "Trying to execute test endpoint..."
-
-    #     for i in $(seq 1 30); do
-    #         response=$(curl -s -o /dev/null -w '%{http_code}' http://localhost:8200/api/insert-data-test/)
+      #   for i in $(seq 1 30); do
+      #       response=$(curl -s -o /dev/null -w '%{http_code}' http://localhost:8200/api/insert-data-test/)
             
-    #         response=$(echo "$response" | tr -d '[:space:]')
+      #       response=$(echo "$response" | tr -d '[:space:]')
 
-    #         echo "HTTP Response: '$response'"
+      #       echo "HTTP Response: '$response'"
 
-    #         if [ "$response" -eq 200 ]; then
-    #             echo "API is ready!"
-    #             exit 0
-    #         else
-    #             echo "Attempt $i: HTTP status $response, Waiting for API to be ready..."
-    #             sleep 3
-    #         fi
-    #     done
+      #       if [ "$response" -eq 200 ]; then
+      #           echo "API is ready!"
+      #           exit 0
+      #       else
+      #           echo "Attempt $i: HTTP status $response, Waiting for API to be ready..."
+      #           sleep 3
+      #       fi
+      #   done
 
-    #     echo "API did not return status code 200 after some attempts."
-    #     exit 1
+      #   echo "API did not return status code 200 after some attempts."
+      #   exit 1
 
     - name: Run dbt models
       run: docker exec dbt-container dbt run
